### ISSUE TITLE
Day numbers start on sunday instead on monday as shown

### ISSUE THREAD

**Issue by JobvdH** [oneyoung/jquery-calendar#2]
The calendar is currently incorrect. It shows Saturday 31th of October while the 31th of October is a Friday. 

mDate.setDate(mDate.getDate() - day) /* now mDate is the start day of the table */

This line is the mistake. By counting +1 on variable day will fix this.

**Comment by akukinakis** [comment]
Hi,

The first day of the month is not displayed if it is Sunday. 
See February and March, 2015.

![calender](https://cloud.githubusercontent.com/assets/11891655/7094959/275e4972-df94-11e4-89e9-e5a05ee17e0c.jpg)

Solution : in calendar.js change the parameter from 1 to 0 in line 59.

THIS :
mDate.setDate(1); /* start of the month */
FOR THIS :
mDate.setDate(0); /* start of the month */

Thank you,
Alex

**Comment by oneyoung** [comment]
Handling week day start from Monday is a little bit tricky,
I prefer to set first day of week to "Sunday", so such problem will gone.
